spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    signerKey: HCzyRdmNHSAuVXVnt26x01KW15acZCCMUaMhe5XpHYiXti6MuaY6M7uohFxHazCe
    expiration: 3600
    refreshable-duration: 36000
    issuer: auth-service

server:
  port: 8080
  servlet:
    context-path: /identity
